package io.github.charlietap.chasm.executor.invoker.dispatch.aggregatefused

import io.github.charlietap.chasm.runtime.dispatch.DispatchableInstruction
import io.github.charlietap.chasm.runtime.instruction.AggregateSuperInstruction

fun AggregateSuperInstructionDispatcher(
    instruction: AggregateSuperInstruction,
): DispatchableInstruction = when (instruction) {
    is AggregateSuperInstruction.ArrayCopyIii -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopyIis -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopyIsi -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopyIss -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopySii -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopySis -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopySsi -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayCopySss -> ArrayCopyDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillIii -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillIis -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillIsi -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillIss -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillSii -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillSis -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillSsi -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayFillSss -> ArrayFillDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetI -> ArrayGetDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetS -> ArrayGetDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetSignedI -> ArrayGetSignedDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetSignedS -> ArrayGetSignedDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetUnsignedI -> ArrayGetUnsignedDispatcher(instruction)
    is AggregateSuperInstruction.ArrayGetUnsignedS -> ArrayGetUnsignedDispatcher(instruction)
    is AggregateSuperInstruction.ArrayLenS -> ArrayLenDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewIi -> ArrayNewDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewIs -> ArrayNewDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewSi -> ArrayNewDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewSs -> ArrayNewDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDefaultI -> ArrayNewDefaultDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDefaultS -> ArrayNewDefaultDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDataIi -> ArrayNewDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDataIs -> ArrayNewDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDataSi -> ArrayNewDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewDataSs -> ArrayNewDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewElementIi -> ArrayNewElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewElementIs -> ArrayNewElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewElementSi -> ArrayNewElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewElementSs -> ArrayNewElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayNewFixedS -> ArrayNewFixedDispatcher(instruction)
    is AggregateSuperInstruction.ArraySetIi -> ArraySetDispatcher(instruction)
    is AggregateSuperInstruction.ArraySetIs -> ArraySetDispatcher(instruction)
    is AggregateSuperInstruction.ArraySetSi -> ArraySetDispatcher(instruction)
    is AggregateSuperInstruction.ArraySetSs -> ArraySetDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataIii -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataIis -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataIsi -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataIss -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataSii -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataSis -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataSsi -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitDataSss -> ArrayInitDataDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementIii -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementIis -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementIsi -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementIss -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementSii -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementSis -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementSsi -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.ArrayInitElementSss -> ArrayInitElementDispatcher(instruction)
    is AggregateSuperInstruction.RefI31I -> RefI31Dispatcher(instruction)
    is AggregateSuperInstruction.RefI31S -> RefI31Dispatcher(instruction)
    is AggregateSuperInstruction.I31GetSignedS -> I31GetSignedDispatcher(instruction)
    is AggregateSuperInstruction.I31GetUnsignedS -> I31GetUnsignedDispatcher(instruction)
    is AggregateSuperInstruction.AnyConvertExternS -> AnyConvertExternDispatcher(instruction)
    is AggregateSuperInstruction.ExternConvertAnyS -> ExternConvertAnyDispatcher(instruction)
    is AggregateSuperInstruction.StructGetS -> StructGetDispatcher(instruction)
    is AggregateSuperInstruction.StructGetSignedS -> StructGetSignedDispatcher(instruction)
    is AggregateSuperInstruction.StructGetUnsignedS -> StructGetUnsignedDispatcher(instruction)
    is AggregateSuperInstruction.RefCastStructGetS -> RefCastStructGetDispatcher(instruction)
    is AggregateSuperInstruction.StructGetStructGetS -> StructGetStructGetDispatcher(instruction)
    is AggregateSuperInstruction.LocalSetStructGetS -> LocalSetStructGetDispatcher(instruction)
    is AggregateSuperInstruction.StructNewS -> StructNewDispatcher(instruction)
    is AggregateSuperInstruction.StructNewDefaultS -> StructNewDefaultDispatcher(instruction)
    is AggregateSuperInstruction.StructSetI -> StructSetDispatcher(instruction)
    is AggregateSuperInstruction.StructSetS -> StructSetDispatcher(instruction)
}
