org.gradle.caching=true
org.gradle.parallel=true
# Re-enable once the build supports Isolated Projects and IDEA-389678 is fixed:
# https://youtrack.jetbrains.com/issue/IDEA-389678
org.gradle.tooling.parallel=false
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.mpp.stability.nowarn=true
