package io.github.charlietap.sweet.plugin.spec

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.buildCodeBlock
import com.squareup.kotlinpoet.joinToCode
import com.squareup.kotlinpoet.withIndent
import io.github.charlietap.sweet.lib.SemanticPhase
import java.io.File

fun testFileSpec(
    phaseSupport: SemanticPhase,
    excludedLines: Set<Int>,
    testPackage: String,
    runner: String,
    script: File,
    test: File,
): FileSpec {

    val runnerClassName = ClassName(runner.substringBeforeLast("."), runner.substringAfterLast("."))
    val scriptResultClassName = ClassName("io.github.charlietap.sweet.lib", "ScriptResult")
    val semanticPhaseClassName = ClassName("io.github.charlietap.sweet.lib", "SemanticPhase")
    val testAnnotation = ClassName("kotlin.test", "Test")
    val assertEqualsFunction = MemberName("kotlin.test", "assertEquals")
    val testClassName = ClassName(testPackage, test.nameWithoutExtension)

    val excludedLineLiterals = excludedLines.sorted()
        .map { CodeBlock.of("%L", it) }
        .joinToCode()
    val runnerArguments = buildCodeBlock {
        add("directory = TEST_DIR,\n")
        add("scriptFilename = %S,\n", script.name)
        add("phaseSupport = %T.%L,\n", semanticPhaseClassName, phaseSupport.name)
        if (excludedLines.isNotEmpty()) {
            add("excludedLines = setOf(%L),\n", excludedLineLiterals)
        }
    }
    val runnerInitializer = buildCodeBlock {
        addStatement("%T(", runnerClassName)
        withIndent {
            add(runnerArguments)
        }
        add(")")
    }
    val runnerProperty = PropertySpec.builder("runner", runnerClassName)
        .initializer(runnerInitializer)
        .addModifiers(KModifier.PRIVATE)
        .build()

    return FileSpec.builder(testClassName.packageName, test.nameWithoutExtension).apply {
        indent("    ")
        addFileComment("Code generated by the wasm testsuite plugin. Do not edit this file.")
        addType(
            TypeSpec.classBuilder(testClassName)
                .addAnnotation(
                    AnnotationSpec.builder(Suppress::class)
                        .addMember("%S", "RedundantVisibilityModifier")
                        .build(),
                )
                .addProperty(runnerProperty)
                .addFunction(
                    FunSpec.builder("script ${script.name.replace(".", " ")} passes successfully")
                        .addAnnotation(testAnnotation)
                        .addStatement("%M(%T.Success, %N.run())", assertEqualsFunction, scriptResultClassName, runnerProperty)
                        .build(),
                )
                .addType(
                    TypeSpec.companionObjectBuilder()
                        .addProperty(
                            PropertySpec.builder("TEST_DIR", String::class)
                                .addModifiers(KModifier.CONST)
                                .initializer("%S", script.parentFile.absolutePath)
                                .build(),
                        )
                        .build(),
                )
                .build(),
        )
    }.build()
}
