package io.github.charlietap.chasm.predecoder.instruction.numericfused

import com.github.michaelbull.result.Result
import io.github.charlietap.chasm.ir.instruction.FusedNumericInstruction
import io.github.charlietap.chasm.predecoder.PredecodingContext
import io.github.charlietap.chasm.runtime.dispatch.DispatchableInstruction
import io.github.charlietap.chasm.runtime.error.ModuleTrapError

internal fun FusedNumericInstructionPredecoder(
    context: PredecodingContext,
    instruction: FusedNumericInstruction,
): Result<DispatchableInstruction, ModuleTrapError> =
    when (instruction) {
        is FusedNumericInstruction.I32Add -> I32AddInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32And -> I32AndInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Or -> I32OrInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Xor -> I32XorInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Sub -> I32SubInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Mul -> I32MulInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32DivS -> I32DivSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32DivU -> I32DivUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Shl -> I32ShlInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32ShrS -> I32ShrSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32ShrU -> I32ShrUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Eq -> I32EqInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Eqz -> I32EqzInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32Ne -> I32NeInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64Eqz -> I64EqzInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Abs -> F32AbsInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64Add -> I64AddInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64Sub -> I64SubInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64Mul -> I64MulInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64DivS -> I64DivSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I64DivU -> I64DivUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Add -> F32AddInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Sub -> F32SubInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Mul -> F32MulInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Div -> F32DivInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Add -> F64AddInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Sub -> F64SubInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Mul -> F64MulInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Div -> F64DivInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32LtS -> I32LtSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32LtU -> I32LtUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32GtS -> I32GtSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32GtU -> I32GtUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32LeS -> I32LeSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32LeU -> I32LeUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32GeS -> I32GeSInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.I32GeU -> I32GeUInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Ge -> F64GeInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F64Lt -> F64LtInstructionPredecoder(context, instruction)
        is FusedNumericInstruction.F32Ceil -> TODO()
        is FusedNumericInstruction.F32ConvertI32S -> TODO()
        is FusedNumericInstruction.F32ConvertI32U -> TODO()
        is FusedNumericInstruction.F32ConvertI64S -> TODO()
        is FusedNumericInstruction.F32ConvertI64U -> TODO()
        is FusedNumericInstruction.F32Copysign -> TODO()
        is FusedNumericInstruction.F32DemoteF64 -> TODO()
        is FusedNumericInstruction.F32Eq -> TODO()
        is FusedNumericInstruction.F32Floor -> TODO()
        is FusedNumericInstruction.F32Ge -> TODO()
        is FusedNumericInstruction.F32Gt -> TODO()
        is FusedNumericInstruction.F32Le -> TODO()
        is FusedNumericInstruction.F32Ne -> TODO()
        is FusedNumericInstruction.F32Nearest -> TODO()
        is FusedNumericInstruction.F32Neg -> TODO()
        is FusedNumericInstruction.F32ReinterpretI32 -> TODO()
        is FusedNumericInstruction.F32Sqrt -> TODO()
        is FusedNumericInstruction.F32Trunc -> TODO()
        is FusedNumericInstruction.F64Abs -> TODO()
        is FusedNumericInstruction.F64Ceil -> TODO()
        is FusedNumericInstruction.F64ConvertI32S -> TODO()
        is FusedNumericInstruction.F64ConvertI32U -> TODO()
        is FusedNumericInstruction.F64ConvertI64S -> TODO()
        is FusedNumericInstruction.F64ConvertI64U -> TODO()
        is FusedNumericInstruction.F64Copysign -> TODO()
        is FusedNumericInstruction.F64Eq -> TODO()
        is FusedNumericInstruction.F64Floor -> TODO()
        is FusedNumericInstruction.F64Ne -> TODO()
        is FusedNumericInstruction.F64Nearest -> TODO()
        is FusedNumericInstruction.F64Neg -> TODO()
        is FusedNumericInstruction.F64PromoteF32 -> TODO()
        is FusedNumericInstruction.F64ReinterpretI64 -> TODO()
        is FusedNumericInstruction.F64Sqrt -> TODO()
        is FusedNumericInstruction.F64Trunc -> TODO()
        is FusedNumericInstruction.I32Clz -> TODO()
        is FusedNumericInstruction.I32Ctz -> TODO()
        is FusedNumericInstruction.I32Extend16S -> TODO()
        is FusedNumericInstruction.I32Extend8S -> TODO()
        is FusedNumericInstruction.I32RemS -> TODO()
        is FusedNumericInstruction.I32RemU -> TODO()
        is FusedNumericInstruction.I32Rotl -> TODO()
        is FusedNumericInstruction.I32Rotr -> TODO()
        is FusedNumericInstruction.I32TruncF32S -> TODO()
        is FusedNumericInstruction.I32TruncF32U -> TODO()
        is FusedNumericInstruction.I32TruncF64S -> TODO()
        is FusedNumericInstruction.I32TruncF64U -> TODO()
        is FusedNumericInstruction.I32TruncSatF32S -> TODO()
        is FusedNumericInstruction.I32TruncSatF32U -> TODO()
        is FusedNumericInstruction.I32TruncSatF64S -> TODO()
        is FusedNumericInstruction.I32TruncSatF64U -> TODO()
        is FusedNumericInstruction.I32WrapI64 -> TODO()
        is FusedNumericInstruction.I64And -> TODO()
        is FusedNumericInstruction.I64Clz -> TODO()
        is FusedNumericInstruction.I64Ctz -> TODO()
        is FusedNumericInstruction.I64Eq -> TODO()
        is FusedNumericInstruction.I64Extend16S -> TODO()
        is FusedNumericInstruction.I64Extend32S -> TODO()
        is FusedNumericInstruction.I64Extend8S -> TODO()
        is FusedNumericInstruction.I64ExtendI32S -> TODO()
        is FusedNumericInstruction.I64ExtendI32U -> TODO()
        is FusedNumericInstruction.I64Ne -> TODO()
        is FusedNumericInstruction.I64Or -> TODO()
        is FusedNumericInstruction.I64Popcnt -> TODO()
        is FusedNumericInstruction.I64ReinterpretF64 -> TODO()
        is FusedNumericInstruction.I64RemS -> TODO()
        is FusedNumericInstruction.I64RemU -> TODO()
        is FusedNumericInstruction.I64Rotl -> TODO()
        is FusedNumericInstruction.I64Rotr -> TODO()
        is FusedNumericInstruction.I64Shl -> TODO()
        is FusedNumericInstruction.I64ShrS -> TODO()
        is FusedNumericInstruction.I64ShrU -> TODO()
        is FusedNumericInstruction.I64TruncF32S -> TODO()
        is FusedNumericInstruction.I64TruncF32U -> TODO()
        is FusedNumericInstruction.I64TruncF64S -> TODO()
        is FusedNumericInstruction.I64TruncF64U -> TODO()
        is FusedNumericInstruction.I64TruncSatF32S -> TODO()
        is FusedNumericInstruction.I64TruncSatF32U -> TODO()
        is FusedNumericInstruction.I64TruncSatF64S -> TODO()
        is FusedNumericInstruction.I64TruncSatF64U -> TODO()
        is FusedNumericInstruction.I64Xor -> TODO()
        is FusedNumericInstruction.F32Lt -> TODO()
        is FusedNumericInstruction.F32Max -> TODO()
        is FusedNumericInstruction.F32Min -> TODO()
        is FusedNumericInstruction.F64Gt -> TODO()
        is FusedNumericInstruction.F64Le -> TODO()
        is FusedNumericInstruction.F64Max -> TODO()
        is FusedNumericInstruction.F64Min -> TODO()
        is FusedNumericInstruction.I32Popcnt -> TODO()
        is FusedNumericInstruction.I32ReinterpretF32 -> TODO()
        is FusedNumericInstruction.I64GeS -> TODO()
        is FusedNumericInstruction.I64GeU -> TODO()
        is FusedNumericInstruction.I64GtS -> TODO()
        is FusedNumericInstruction.I64GtU -> TODO()
        is FusedNumericInstruction.I64LeS -> TODO()
        is FusedNumericInstruction.I64LeU -> TODO()
        is FusedNumericInstruction.I64LtS -> TODO()
        is FusedNumericInstruction.I64LtU -> TODO()
    }
