package io.github.charlietap.chasm.executor.invoker.dispatch.aggregate

import io.github.charlietap.chasm.runtime.dispatch.DispatchableInstruction
import io.github.charlietap.chasm.runtime.instruction.AggregateInstruction

fun AggregateInstructionDispatcher(
    instruction: AggregateInstruction,
): DispatchableInstruction = when (instruction) {
    is AggregateInstruction.ArrayCopyIii -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopyIis -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopyIsi -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopyIss -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopySii -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopySis -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopySsi -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayCopySss -> ArrayCopyDispatcher(instruction)
    is AggregateInstruction.ArrayFillIii -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillIis -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillIsi -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillIss -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillSii -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillSis -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillSsi -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayFillSss -> ArrayFillDispatcher(instruction)
    is AggregateInstruction.ArrayGetI -> ArrayGetDispatcher(instruction)
    is AggregateInstruction.ArrayGetS -> ArrayGetDispatcher(instruction)
    is AggregateInstruction.ArrayGetSignedI -> ArrayGetSignedDispatcher(instruction)
    is AggregateInstruction.ArrayGetSignedS -> ArrayGetSignedDispatcher(instruction)
    is AggregateInstruction.ArrayGetUnsignedI -> ArrayGetUnsignedDispatcher(instruction)
    is AggregateInstruction.ArrayGetUnsignedS -> ArrayGetUnsignedDispatcher(instruction)
    is AggregateInstruction.ArrayLenS -> ArrayLenDispatcher(instruction)
    is AggregateInstruction.ArrayNewIi -> ArrayNewDispatcher(instruction)
    is AggregateInstruction.ArrayNewIs -> ArrayNewDispatcher(instruction)
    is AggregateInstruction.ArrayNewSi -> ArrayNewDispatcher(instruction)
    is AggregateInstruction.ArrayNewSs -> ArrayNewDispatcher(instruction)
    is AggregateInstruction.ArrayNewDefaultI -> ArrayNewDefaultDispatcher(instruction)
    is AggregateInstruction.ArrayNewDefaultS -> ArrayNewDefaultDispatcher(instruction)
    is AggregateInstruction.ArrayNewDataIi -> ArrayNewDataDispatcher(instruction)
    is AggregateInstruction.ArrayNewDataIs -> ArrayNewDataDispatcher(instruction)
    is AggregateInstruction.ArrayNewDataSi -> ArrayNewDataDispatcher(instruction)
    is AggregateInstruction.ArrayNewDataSs -> ArrayNewDataDispatcher(instruction)
    is AggregateInstruction.ArrayNewElementIi -> ArrayNewElementDispatcher(instruction)
    is AggregateInstruction.ArrayNewElementIs -> ArrayNewElementDispatcher(instruction)
    is AggregateInstruction.ArrayNewElementSi -> ArrayNewElementDispatcher(instruction)
    is AggregateInstruction.ArrayNewElementSs -> ArrayNewElementDispatcher(instruction)
    is AggregateInstruction.ArrayNewFixedS -> ArrayNewFixedDispatcher(instruction)
    is AggregateInstruction.ArraySetIi -> ArraySetDispatcher(instruction)
    is AggregateInstruction.ArraySetIs -> ArraySetDispatcher(instruction)
    is AggregateInstruction.ArraySetSi -> ArraySetDispatcher(instruction)
    is AggregateInstruction.ArraySetSs -> ArraySetDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataIii -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataIis -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataIsi -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataIss -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataSii -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataSis -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataSsi -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitDataSss -> ArrayInitDataDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementIii -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementIis -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementIsi -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementIss -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementSii -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementSis -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementSsi -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.ArrayInitElementSss -> ArrayInitElementDispatcher(instruction)
    is AggregateInstruction.RefI31I -> RefI31Dispatcher(instruction)
    is AggregateInstruction.RefI31S -> RefI31Dispatcher(instruction)
    is AggregateInstruction.I31GetSignedS -> I31GetSignedDispatcher(instruction)
    is AggregateInstruction.I31GetUnsignedS -> I31GetUnsignedDispatcher(instruction)
    is AggregateInstruction.AnyConvertExternS -> AnyConvertExternDispatcher(instruction)
    is AggregateInstruction.ExternConvertAnyS -> ExternConvertAnyDispatcher(instruction)
    is AggregateInstruction.StructGetS -> StructGetDispatcher(instruction)
    is AggregateInstruction.StructGetSignedS -> StructGetSignedDispatcher(instruction)
    is AggregateInstruction.StructGetUnsignedS -> StructGetUnsignedDispatcher(instruction)
    is AggregateInstruction.RefCastStructGetS -> RefCastStructGetDispatcher(instruction)
    is AggregateInstruction.StructGetStructGetS -> StructGetStructGetDispatcher(instruction)
    is AggregateInstruction.LocalSetStructGetS -> LocalSetStructGetDispatcher(instruction)
    is AggregateInstruction.StructNewS -> StructNewDispatcher(instruction)
    is AggregateInstruction.StructNewDefaultS -> StructNewDefaultDispatcher(instruction)
    is AggregateInstruction.StructSetI -> StructSetDispatcher(instruction)
    is AggregateInstruction.StructSetS -> StructSetDispatcher(instruction)
}
