package io.github.charlietap.corpus.plugin.task

import io.github.charlietap.corpus.lib.CorpusPhase
import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateCorpusTestsTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val fixturesIndex: RegularFileProperty

    @get:Input
    abstract val corpusRunner: Property<String>

    @get:Input
    abstract val testPackageName: Property<String>

    @get:Input
    abstract val phase: Property<CorpusPhase>

    @get:Input
    abstract val targets: ListProperty<String>

    @get:Input
    abstract val excludedTargets: ListProperty<String>

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val corpusDirectory: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val outputDir = outputDirectory.get().asFile
        outputDir.deleteRecursively()
        outputDir.mkdirs()

        val fixtures = Json.parseToJsonElement(fixturesIndex.get().asFile.readText()).jsonArray
        fixtures
            .map { it as JsonObject }
            .filter(::targetMatches)
            .filterNot(::targetExcluded)
            .forEach(::writeTest)
    }

    private fun targetMatches(fixture: JsonObject): Boolean {
        val selected = targets.get()
        if (selected.isEmpty()) return true
        val name = fixture.string("name")
        val path = fixture.string("path")
        val stem = path.substringAfterLast('/').substringBeforeLast(".")
        return selected.any { target -> target == name || target == path || target == stem }
    }

    private fun targetExcluded(fixture: JsonObject): Boolean {
        val excluded = excludedTargets.get()
        if (excluded.isEmpty()) return false
        val name = fixture.string("name")
        val path = fixture.string("path")
        val stem = path.substringAfterLast('/').substringBeforeLast(".")
        return excluded.any { target -> target == name || target == path || target == stem }
    }

    private fun writeTest(fixture: JsonObject) {
        val name = fixture.string("name")
        val version = fixture.string("version")
        val path = fixture.string("path")
        val packageName = "${testPackageName.get()}.v${version.replace(".", "_")}.${name.packageSegment()}"
        val className = "${name.pascalCase()}Test"
        val packagePath = packageName.replace(".", File.separator)
        val outputFile = outputDirectory.get().asFile.resolve(packagePath).resolve("$className.kt")
        val runnerClass = corpusRunner.get().substringAfterLast(".")
        val runnerPackage = corpusRunner.get().substringBeforeLast(".")
        val fixtureJsonPath = path.replace(Regex("\\.wasm$"), ".json")

        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            """
            |// Code generated by the wasm corpus plugin. Do not edit this file.
            |package $packageName
            |
            |import $runnerPackage.$runnerClass
            |import io.github.charlietap.corpus.lib.CorpusPhase
            |import io.github.charlietap.corpus.lib.CorpusResult
            |import io.github.charlietap.corpus.lib.fixture.Fixture
            |import kotlin.test.Test
            |import kotlin.test.assertEquals
            |import kotlinx.serialization.json.Json
            |
            |class $className {
            |    private val runner = $runnerClass()
            |
            |    @Test
            |    fun `fixture $name passes corpus ${phase.get().name.lowercase()}`() {
            |        val fixture = Json { ignoreUnknownKeys = true }
            |            .decodeFromString<Fixture>(runner.readText(FIXTURE_JSON))
            |            .copy(version = CORPUS_VERSION)
            |        val result = runner.execute(CORPUS_ROOT, fixture, CorpusPhase.${phase.get().name})
            |        if (result is CorpusResult.Skipped) {
            |            println("Skipped wasm-corpus fixture $name: ${'$'}{result.reason}")
            |            return
            |        }
            |
            |        assertEquals(CorpusResult.Success, result)
            |    }
            |
            |    companion object {
            |        const val CORPUS_VERSION = "$version"
            |        const val CORPUS_ROOT = "${corpusDirectory.get().asFile.absolutePath}"
            |        const val FIXTURE_JSON = "${corpusDirectory.get().asFile.resolve(version).resolve(fixtureJsonPath).absolutePath}"
            |    }
            |}
            |
            """.trimMargin(),
        )
    }

    private fun JsonObject.string(name: String): String = getValue(name).jsonPrimitive.content

    private fun String.packageSegment(): String = replace(Regex("[^A-Za-z0-9_]"), "_")
        .let { if (it.firstOrNull()?.isDigit() == true) "_$it" else it }
        .lowercase()

    private fun String.pascalCase(): String = split(Regex("[^A-Za-z0-9]+"))
        .filter(String::isNotBlank)
        .joinToString("") { part -> part.replaceFirstChar(Char::uppercaseChar) }
        .let { if (it.firstOrNull()?.isDigit() == true) "_$it" else it }
}
