package io.github.charlietap.corpus.plugin.task

import com.squareup.kotlinpoet.CodeBlock
import io.github.charlietap.corpus.lib.CorpusPhase
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateCorpusTestsTask : DefaultTask() {

    @get:Input
    abstract val corpusRunner: Property<String>

    @get:Input
    abstract val testPackageName: Property<String>

    @get:Input
    abstract val phase: Property<CorpusPhase>

    @get:Input
    abstract val resultsDirectoryPath: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val output = outputDirectory.file("CorpusTest.kt").get().asFile
        val runnerClass = corpusRunner.get().substringAfterLast('.')
        val runnerPackage = corpusRunner.get().substringBeforeLast('.')
        val phase = phase.get()

        outputDirectory.get().asFile.deleteRecursively()
        output.parentFile.mkdirs()
        output.writeText(
            """
            |// Code generated by the wasm corpus plugin. Do not edit this file.
            |package ${testPackageName.get()}
            |
            |import $runnerPackage.$runnerClass
            |import io.github.charlietap.corpus.lib.CorpusPhase
            |import io.github.charlietap.corpus.lib.CorpusResult
            |import io.github.charlietap.corpus.lib.ResourceCorpusFileReader
            |import io.github.charlietap.corpus.lib.fixture.Fixture
            |import io.github.charlietap.corpus.lib.report.CorpusFixtureResult
            |import io.github.charlietap.corpus.lib.report.CorpusReportWriter
            |import java.nio.file.Path
            |import kotlin.test.Test
            |import kotlin.test.assertTrue
            |import kotlinx.serialization.json.Json
            |import kotlinx.serialization.json.jsonArray
            |import kotlinx.serialization.json.jsonObject
            |import kotlinx.serialization.json.jsonPrimitive
            |
            |class CorpusTest {
            |    private val runner = $runnerClass(ResourceCorpusFileReader())
            |    private val reportWriter = CorpusReportWriter()
            |    private val json = Json { ignoreUnknownKeys = true }
            |
            |    @Test
            |    fun fixturesPassCorpus${phase.name.lowercase().replaceFirstChar(Char::uppercase)}() {
            |        val failures = mutableListOf<String>()
            |        val fixtures = json.parseToJsonElement(runner.readText(FIXTURE_INDEX)).jsonArray
            |        fixtures.forEach { element ->
            |            val descriptor = element.jsonObject
            |            val version = descriptor.getValue("version").jsonPrimitive.content
            |            val path = descriptor.getValue("path").jsonPrimitive.content
            |            val fixturePath = "corpus/${'$'}version/${'$'}{path.removeSuffix(".wasm")}.json"
            |            val fixture = json.decodeFromString<Fixture>(runner.readText(fixturePath))
            |                .copy(version = version)
            |            val execution = runner.execute(CORPUS_ROOT, fixture, CorpusPhase.${phase.name})
            |            reportWriter.write(
            |                Path.of(RESULTS_DIRECTORY),
            |                CorpusFixtureResult.from(fixture, CorpusPhase.${phase.name}, execution),
            |            )
            |            when (val result = execution.result) {
            |                CorpusResult.Success -> Unit
            |                is CorpusResult.Skipped -> println(
            |                    "Skipped wasm-corpus fixture ${'$'}{fixture.name}: ${'$'}{result.reason}",
            |                )
            |                is CorpusResult.Failure -> failures += "${'$'}{fixture.name}: ${'$'}result"
            |            }
            |        }
            |
            |        assertTrue(failures.isEmpty(), failures.joinToString(separator = "\n"))
            |    }
            |
            |    companion object {
            |        const val CORPUS_ROOT = "corpus"
            |        const val FIXTURE_INDEX = "corpus/fixtures.json"
            |        const val RESULTS_DIRECTORY = ${resultsDirectoryPath.get().quoted()}
            |    }
            |}
            |
            """.trimMargin(),
        )
    }

    private fun String.quoted(): String = CodeBlock.of("%S", this).toString()
}
