name: Build 🔨

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true
  workflow_dispatch:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up jdk@21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Setup WABT
        uses: mwilliamson/setup-wabt-action@v2
        with:
          wabt-version: "1.0.34"

      - name: Execute Gradle build
        run: ./gradlew build
