name: Pull Request and Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    uses: ./.github/workflows/build.yml
    with:
      runner: ${{ matrix.os }}
