name: Pull Request and Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:

  generate-matrix:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: macos-latest
      task: testMatrix
      result: true

  testresult:
    runs-on: ubuntu-latest
    needs: generate-matrix
    steps:
      - run: echo ${{needs.generate-matrix.outputs.result}}

  build:
    needs: generate-matrix
    strategy:
      matrix:
        include:
          - os: macos-latest
            task: jvmTest
          - os: macos-latest
            task: macosArm64Test
          - os: macos-latest
            task: iosSimulatorArm64Test
          - os: ubuntu-latest
            task: linuxX64Test
          - os: windows-latest
            task: mingwX64Test
    uses: ./.github/workflows/testsuite-matrix.yml
    with:
      matrix: ${{ needs.generate-matrix.outputs.result }}
      runner: ${{ matrix.os }}
      task: ${{ matrix.task }}

  lint:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ubuntu-latest
      task: lintKotlin
