name: Pull Request and Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:

  abi:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ubuntu-24.04
      task: checkLegacyAbi

  lint:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ubuntu-24.04-arm
      task: lintKotlin

  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            task: jvmTest
          - os: macos-latest
            task: macosArm64Test
          - os: macos-latest
            task: iosSimulatorArm64Test
          - os: ubuntu-latest
            task: linuxX64Test
          - os: windows-latest
            task: mingwX64Test
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ${{ matrix.os }}
      task: ${{ matrix.task }}
