name: Pull Request and Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            task: jvmTest
          - os: macos-latest
            task: macosArm64Test
          - os: macos-latest
            task: iosSimulatorArm64Test
          - os: ubuntu-latest
            task: linuxX64Test
          - os: windows-latest
            task: mingwX64Test
    uses: ./.github/workflows/testsuite-matrix.yml
    with:
      runner: ${{ matrix.os }}
      task: ${{ matrix.task }}

  lint:
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: macos-latest
      task: lintKotlin
