name: Gradle task workflow 🔨

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true
      task:
        type: string
        description: 'The gradle task to run'
        default: build
        required: true
      result:
        type: boolean
        description: 'If the workflow has an output result'
        default: false
        required: false
    outputs:
      result:
        description: "The result from the task execution"
        value: ${{ jobs.task.outputs.result }}
  workflow_dispatch:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true
      task:
        type: string
        description: 'The gradle task to run'
        default: build
        required: true
      result:
        type: boolean
        description: 'If the workflow has an output result'
        default: false
        required: false

jobs:
  task:
    outputs:
      result: ${{ steps.result.outputs.result }}
    runs-on: ${{ inputs.runner }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up jdk@21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Execute Gradle task
        if: ${{ !inputs.result }}
        run: ./gradlew ${{ inputs.task }}

      - name: Execute Gradle task with result
        id: result
        if: ${{ inputs.result }}
        run: |
          RESULT=$(./gradlew -q ${{ inputs.task }})
          echo $RESULT
          echo "result=${RESULT}" >> $GITHUB_OUTPUT
