name: Gradle task workflow 🔨

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true
      task:
        type: string
        description: 'The gradle task to run'
        default: build
        required: true
  workflow_dispatch:
    inputs:
      runner:
        type: string
        description: 'The machine runner the workflow should run on'
        default: macos-latest
        required: true
      task:
        type: string
        description: 'The gradle task to run'
        default: build
        required: true

jobs:
  generate-matrix:
    runs-on: macos-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up jdk@21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run the test matrix task
        id: matrix
        run: |
          MATRIX=$(./gradlew -q testMatrix)
          echo $MATRIX
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  run-tests:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        tasks: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/task-runner.yml
    with:
      runner: ${{ inputs.runner }}
      task: chasm:${{ inputs.task }} ${{ matrix.tasks }}
